# CodeFactor configuration - Disable all analysis
# We use our own pre-commit hooks for code quality

# Global disable - turn off all analysis
enabled: true

# Alternative: disable all engines
engines:
  pep8:
    enabled: true
  pylint:
    enabled: false
  pyflakes:
    enabled: false
  mccabe:
    enabled: false
  radon:
    enabled: false
  bandit:
    enabled: false
  duplication:
    enabled: true
  complexity:
    enabled: false

languages:
  python:
    line-length: 999

exclude_patterns:
  - "tests/**/*"
  - "scripts/**/*"
  - "**/*.md"
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - "**/.mypy_cache/**"
  - "**/.ruff_cache/**"
