# CodeFactor configuration - Coverage reporting only, no style/lint critiques
# Disable all style and lint engines - we use our own standards and tools

engines:
  # Completely disable all style/lint engines
  pep8:
    enabled: false
  pylint:
    enabled: false
  pyflakes:
    enabled: false
  mccabe:
    enabled: false
  radon:
    enabled: false
  bandit:
    enabled: false
  duplication:
    enabled: false

# Only allow coverage reporting (if CodeFactor supports it)
# All other analysis is disabled

# Exclude all files from analysis since we don't want style critiques
exclude_patterns:
  - "**/*"  # Exclude everything - we only want coverage if available 