# CodeFactor configuration - DISABLED
# We use our own comprehensive pre-commit hooks for all code quality checks:
# - ruff (formatting, linting, import sorting)
# - mypy (type checking)
# - bandit (security)
# - radon (complexity)
# - pytest with coverage
# - markdownlint
# - pre-commit hooks for file validation

# Disable CodeFactor entirely
enabled: false
