---
# Exclude specific directories or files
FILTER_REGEX_EXCLUDE: ".direnv/**|env/**|**/site-packages/**|custom_components/span_panel/translations/**"

# Include only specific directories or files
FILTER_REGEX_INCLUDE: "custom_components/span_panel/.*\\.(py|json)$|\\.(html|md)$"

# Ensure Python and JSON linters are enabled
VALIDATE_PYTHON: true
VALIDATE_JSON: true
VALIDATE_MARKDOWN: true
VALIDATE_MARKUP: true