---
name: HACS Jobs

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  validate:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    if: "github.head_ref == 'main' || github.ref == 'refs/heads/main'"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: integration
