---
name: Lint Code Base

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  actions: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Run isort
        run: isort .

      - name: Run Black
        run: black .

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
