name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call: {} # Allow this workflow to be called by other workflows

permissions:
  contents: read
  checks: write
  actions: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort mypy bandit prettier

      - name: Run ruff
        run: ruff check .

      - name: Run isort
        run: isort check .

      - name: Run bandit
        run: bandit -r .

      - name: Run prettier
        run: prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,md}"
