name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  hacs:
    needs: ci
    uses: ./.github/workflows/hacs.yml

