---
name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write
  checks: write
  actions: read

jobs:
  lint:
    name: Lint Code Base
    uses: ./.github/workflows/lint.yml

  hacs:
    name: HACS Action
    needs: lint
    uses: ./.github/workflows/hacs.yml
