---
name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write
  checks: write
  actions: read

jobs:
  validate:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"

  lint:
    name: Lint Code Base
    uses: ./.github/workflows/lint.yml
